apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prod
  region: ap-northeast-2
  version: "1.31"

vpc:
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    publicAccess: true   # 퍼블릭 엔드포인트 비활성화
    privateAccess: true   # 프라이빗 엔드포인트 활성화  

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: eks-service-account
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    maxSize: 4           # 선택 사항: 최대 크기 정의
    minSize: 1           # 선택 사항: 최소 크기 정의
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: SecondFit-TestDB-EC2

# addons:
#   - name: vpc-cni
#     podIdentityAssociations:
#       - namespace: default
#         permissionPolicyARNs: ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
#         serviceAccountName: eks-service-account
#   - name: eks-pod-identity-agent
#     version: latest

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy