apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prod
  region: ap-northeast-2
  version: "1.31"

vpc:
  nat:
    gateway: HighlyAvailable
  

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: eks-service-account
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    maxSize: 4           # 선택 사항: 최대 크기 정의
    minSize: 1           # 선택 사항: 최소 크기 정의
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: SecondFit-TestDB-EC2

addons:
- name: vpc-cni
  podIdentityAssociations:
  - namespace: kube-system
    permissionPolicyARNs: ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
    serviceAccountName: aws-node
# 필요한 경우 다른 애드온 추가