resources:
- ../../base
configMapGenerator:
- behavior: merge
  envs:
  - conf/app.env
  name: app-env-vars
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: dev
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
