# api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondfit-api-server-deployment
spec:
  selector:
    matchLabels:
      run: secondfit-api-server-pod
  replicas: 2
  template:
    metadata:
      labels:
        run: secondfit-api-server-pod
    spec:
      containers:
      - name: secondfit-api-server-container
        image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest
        ports:
        - containerPort: 80