# api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondfit-api-server-deployment
spec:
  selector:
    matchLabels:
      run: secondfit-api-server-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: secondfit-api-server-pod
    spec:
      containers:
      - name: secondfit-api-server-container
        image: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/prod/api-server:de4e1c2a4b259fd31632ffdf1aea58d777479363
        ports:
        - containerPort: 3005
      imagePullSecrets:
      - name: ecr-secret
