# api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondfit-api-server-deployment
spec:
  selector:
    matchLabels:
      run: secondfit-api-server-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: secondfit-api-server-pod
    spec:
      containers:
      - name: secondfit-api-server-container
        image: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/dev/api-servier:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80