resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/prod/api-server
  newName: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/prod/api-server
  newTag: b63de2b28e3c4cbe68d67dbb9b855317174afb31
