resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/prod/api-server
  newName: 886436932322.dkr.ecr.ap-northeast-2.amazonaws.com/prod/api-server
  newTag: 5e625f4e02e4d825d8ca3ccdc11e82daace4fa32
