apiVersion: v1
kind: Service
metadata:
  name: secondfit-api-server-svc
  labels:
    run: secondfit-api-server-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: secondfit-api-server-pod